#!/usr/bin/env bash

# Dagster Workflows Configuration Wizard
# This script helps configure InfluxDB and Tibber API connections

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

INSTALL_DIR="/opt/dagster-workflows/nebenkosten"
INFLUX_ENV="$INSTALL_DIR/secrets/influxdb.env"
TIBBER_ENV="$INSTALL_DIR/secrets/tibber.env"
CONFIG_YAML="$INSTALL_DIR/config/config.yaml"

echo -e "${BLUE}╔════════════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║     Dagster Workflows Configuration Wizard                ║${NC}"
echo -e "${BLUE}╚════════════════════════════════════════════════════════════╝${NC}\n"

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    echo -e "${RED}Error: This script must be run as root${NC}"
    exit 1
fi

# Check if installation directory exists
if [ ! -d "$INSTALL_DIR" ]; then
    echo -e "${RED}Error: Installation directory not found: $INSTALL_DIR${NC}"
    echo -e "${YELLOW}Please ensure Dagster workflows are properly installed.${NC}"
    exit 1
fi

cd "$INSTALL_DIR"

echo -e "${YELLOW}This wizard will help you configure:${NC}"
echo -e "  1. InfluxDB connection (required)"
echo -e "  2. Tibber API (optional)"
echo -e "  3. Configuration parameters\n"

# ============================================================================
# InfluxDB Configuration
# ============================================================================

echo -e "${BLUE}━━━ InfluxDB Configuration ━━━${NC}\n"

# Load existing values if available
if [ -f "$INFLUX_ENV" ]; then
    source "$INFLUX_ENV"
fi

# InfluxDB URL
echo -e "${YELLOW}InfluxDB URL${NC}"
echo -e "Example: http://192.168.1.75:8086"
if [ -n "$INFLUX_URL" ]; then
    echo -e "Current: $INFLUX_URL"
    read -p "Press Enter to keep current value, or enter new URL: " NEW_URL
    INFLUX_URL="${NEW_URL:-$INFLUX_URL}"
else
    read -p "Enter InfluxDB URL: " INFLUX_URL
fi

# InfluxDB Token
echo -e "\n${YELLOW}InfluxDB Token${NC}"
echo -e "Get this from InfluxDB UI: Data → API Tokens"
if [ -n "$INFLUX_TOKEN" ] && [ "$INFLUX_TOKEN" != "your-influxdb-token-here" ]; then
    echo -e "Current token is set (hidden)"
    read -p "Press Enter to keep current token, or enter new token: " NEW_TOKEN
    INFLUX_TOKEN="${NEW_TOKEN:-$INFLUX_TOKEN}"
else
    read -p "Enter InfluxDB Token: " INFLUX_TOKEN
fi

# InfluxDB Organization
echo -e "\n${YELLOW}InfluxDB Organization${NC}"
if [ -n "$INFLUX_ORG" ] && [ "$INFLUX_ORG" != "your-org-name" ]; then
    echo -e "Current: $INFLUX_ORG"
    read -p "Press Enter to keep current value, or enter new organization: " NEW_ORG
    INFLUX_ORG="${NEW_ORG:-$INFLUX_ORG}"
else
    read -p "Enter InfluxDB Organization: " INFLUX_ORG
fi

# InfluxDB Bucket Raw
echo -e "\n${YELLOW}InfluxDB Raw Data Bucket${NC}"
if [ -n "$INFLUX_BUCKET_RAW" ]; then
    echo -e "Current: $INFLUX_BUCKET_RAW"
    read -p "Press Enter to keep current value, or enter new bucket name: " NEW_BUCKET
    INFLUX_BUCKET_RAW="${NEW_BUCKET:-$INFLUX_BUCKET_RAW}"
else
    read -p "Enter raw data bucket name [lampfi]: " INFLUX_BUCKET_RAW
    INFLUX_BUCKET_RAW="${INFLUX_BUCKET_RAW:-lampfi}"
fi

# InfluxDB Bucket Processed
echo -e "\n${YELLOW}InfluxDB Processed Data Bucket${NC}"
if [ -n "$INFLUX_BUCKET_PROCESSED" ]; then
    echo -e "Current: $INFLUX_BUCKET_PROCESSED"
    read -p "Press Enter to keep current value, or enter new bucket name: " NEW_BUCKET
    INFLUX_BUCKET_PROCESSED="${NEW_BUCKET:-$INFLUX_BUCKET_PROCESSED}"
else
    read -p "Enter processed data bucket name [lampfi_processed]: " INFLUX_BUCKET_PROCESSED
    INFLUX_BUCKET_PROCESSED="${INFLUX_BUCKET_PROCESSED:-lampfi_processed}"
fi

# Write InfluxDB configuration
echo -e "\n${BLUE}Writing InfluxDB configuration...${NC}"
cat > "$INFLUX_ENV" <<EOF
# InfluxDB Configuration
# Generated by configure-dagster on $(date)

# InfluxDB Authentication Token
INFLUX_TOKEN=$INFLUX_TOKEN

# InfluxDB Organization Name
INFLUX_ORG=$INFLUX_ORG

# InfluxDB URL
INFLUX_URL=$INFLUX_URL

# Bucket names
INFLUX_BUCKET_RAW=$INFLUX_BUCKET_RAW
INFLUX_BUCKET_PROCESSED=$INFLUX_BUCKET_PROCESSED
EOF

chmod 600 "$INFLUX_ENV"
echo -e "${GREEN}✓ InfluxDB configuration saved${NC}"

# Test InfluxDB connection
echo -e "\n${BLUE}Testing InfluxDB connection...${NC}"
HEALTH_CHECK=$(curl -s -o /dev/null -w "%{http_code}" "${INFLUX_URL}/health" || echo "000")

if [ "$HEALTH_CHECK" = "200" ]; then
    echo -e "${GREEN}✓ InfluxDB is reachable${NC}"
else
    echo -e "${YELLOW}⚠ Warning: Could not connect to InfluxDB${NC}"
    echo -e "${YELLOW}  Please verify the URL and ensure InfluxDB is running${NC}"
fi

# ============================================================================
# Tibber API Configuration (Optional)
# ============================================================================

echo -e "\n${BLUE}━━━ Tibber API Configuration (Optional) ━━━${NC}\n"
echo -e "${YELLOW}Do you want to configure Tibber API for electricity sync?${NC}"
read -p "Configure Tibber? [y/N]: " CONFIGURE_TIBBER

if [[ "$CONFIGURE_TIBBER" =~ ^[Yy]$ ]]; then
    # Load existing values if available
    if [ -f "$TIBBER_ENV" ]; then
        source "$TIBBER_ENV"
    fi

    echo -e "\n${YELLOW}Tibber API Token${NC}"
    echo -e "Get this from: https://developer.tibber.com/settings/access-token"
    if [ -n "$TIBBER_API_TOKEN" ] && [ "$TIBBER_API_TOKEN" != "your-tibber-api-token-here" ]; then
        echo -e "Current token is set (hidden)"
        read -p "Press Enter to keep current token, or enter new token: " NEW_TOKEN
        TIBBER_API_TOKEN="${NEW_TOKEN:-$TIBBER_API_TOKEN}"
    else
        read -p "Enter Tibber API Token: " TIBBER_API_TOKEN
    fi

    # Write Tibber configuration
    echo -e "\n${BLUE}Writing Tibber configuration...${NC}"
    cat > "$TIBBER_ENV" <<EOF
# Tibber API Configuration
# Generated by configure-dagster on $(date)

# Tibber API Token
TIBBER_API_TOKEN=$TIBBER_API_TOKEN
EOF

    chmod 600 "$TIBBER_ENV"
    echo -e "${GREEN}✓ Tibber configuration saved${NC}"
else
    echo -e "${BLUE}Skipping Tibber configuration${NC}"
fi

# ============================================================================
# Update config.yaml
# ============================================================================

echo -e "\n${BLUE}━━━ Updating Configuration File ━━━${NC}\n"

cat > "$CONFIG_YAML" <<EOF
# Dagster Workflows Configuration
# Generated by configure-dagster on $(date)

influx:
  url: "$INFLUX_URL"
  bucket_raw: "$INFLUX_BUCKET_RAW"
  bucket_processed: "$INFLUX_BUCKET_PROCESSED"
  timeout: 30000
  retry_attempts: 3

# Start year for historical data processing
start_year: 2020

# Processing settings
processing:
  enable_anomaly_detection: true
  interpolation_method: "linear"
EOF

echo -e "${GREEN}✓ Configuration file updated${NC}"

# ============================================================================
# Restart Services
# ============================================================================

echo -e "\n${BLUE}━━━ Restarting Dagster Services ━━━${NC}\n"
echo -e "${YELLOW}Restarting containers to apply new configuration...${NC}"

cd "$INSTALL_DIR"
docker compose -f docker-compose.dagster.yml restart

echo -e "${GREEN}✓ Services restarted${NC}"

# Wait for services to be healthy
echo -e "\n${BLUE}Waiting for services to be ready...${NC}"
sleep 10

# Check service status
if docker ps | grep -q dagster-webserver; then
    echo -e "${GREEN}✓ Dagster services are running${NC}"
else
    echo -e "${YELLOW}⚠ Warning: Services may still be starting${NC}"
    echo -e "  Check status with: docker ps"
fi

# ============================================================================
# Summary
# ============================================================================

IP_ADDR=$(hostname -I | awk '{print $1}')

echo -e "\n${GREEN}╔════════════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║         Configuration Complete!                            ║${NC}"
echo -e "${GREEN}╚════════════════════════════════════════════════════════════╝${NC}\n"

echo -e "${BLUE}Dagster UI:${NC} ${GREEN}http://$IP_ADDR:3000${NC}\n"

echo -e "${YELLOW}Next Steps:${NC}"
echo -e "  1. Open the Dagster UI in your browser"
echo -e "  2. Navigate to ${BLUE}Automation → Schedules${NC}"
echo -e "  3. Enable schedules:"
echo -e "     - ${BLUE}analytics_daily${NC} (recommended)"
if [[ "$CONFIGURE_TIBBER" =~ ^[Yy]$ ]]; then
    echo -e "     - ${BLUE}tibber_sync_hourly${NC} (for Tibber data)"
fi
echo -e "  4. Or manually run jobs from the ${BLUE}Jobs${NC} tab\n"

echo -e "${YELLOW}Useful Commands:${NC}"
echo -e "  View logs: ${BLUE}docker compose -f docker-compose.dagster.yml logs -f${NC}"
echo -e "  Check status: ${BLUE}docker ps${NC}"
echo -e "  Restart: ${BLUE}docker compose -f docker-compose.dagster.yml restart${NC}\n"

echo -e "${GREEN}Configuration files saved to:${NC}"
echo -e "  - $INFLUX_ENV"
if [[ "$CONFIGURE_TIBBER" =~ ^[Yy]$ ]]; then
    echo -e "  - $TIBBER_ENV"
fi
echo -e "  - $CONFIG_YAML\n"
