# .gitea/workflows/deploy.yml
name: Deploy Water Temp Sync

on:
  push:
    branches:
      - main # Trigger on push to the main branch (or 'master' if that's your default)

jobs:
  deploy:
    # Use the labels you assigned to your self-hosted runner during registration.
    # E.g., if you used --labels linux,x64,alpine,deploy
    runs-on: [linux, x64, alpine, deploy]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Action to clone your repository onto the runner

      - name: Setup SSH key for deployment
        run: |
          mkdir -p ~/.ssh
          # Write the private key from Gitea secret to a file
          echo "${{ secrets.SSH_PRIVATE_KEY_DEPLOY }}" > ~/.ssh/id_rsa_deploy
          chmod 600 ~/.ssh/id_rsa_deploy
          # Start ssh-agent and add the key to it
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa_deploy
          # Add the target host to known_hosts to avoid first-time connection prompts
          # REPLACE 192.168.1.101 WITH YOUR TARGET ALPINE MACHINE'S IP!
          ssh-keyscan -H 192.168.1.101 >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts # Ensure correct permissions
        env:
          # The secret value is passed as an environment variable
          SSH_PRIVATE_KEY_DEPLOY: ${{ secrets.SSH_PRIVATE_KEY_DEPLOY }}

      - name: Deploy and setup on Alpine machine
        run: |
          # Define the target IP
          TARGET_IP="192.168.1.101" # REPLACE THIS WITH YOUR TARGET ALPINE MACHINE'S IP!
          TEMP_DEPLOY_DIR="/tmp/water_temp_deploy"
          SSH_KEY="~/.ssh/id_rsa_deploy"

          echo "Deploying to root@$TARGET_IP..."

          # Create temporary deploy directory on target
          ssh -i "$SSH_KEY" root@"$TARGET_IP" "mkdir -p $TEMP_DEPLOY_DIR"

          # Copy files using rsync
          rsync -avz -e "ssh -i $SSH_KEY" \
            --exclude '.git/' \
            --exclude '.gitea/' \
            ./getWaterTemp.py \
            ./cron_setup.sh \
            root@"$TARGET_IP":"$TEMP_DEPLOY_DIR/"

          echo "Files copied. Now executing setup script on target..."

          # SSH into the Alpine machine and run the setup script
          ssh -i "$SSH_KEY" root@"$TARGET_IP" " \
            cd $TEMP_DEPLOY_DIR && \
            chmod +x cron_setup.sh && \
            ./cron_setup.sh && \
            echo 'Deployment script finished. Cleaning up temporary directory...' && \
            rm -rf $TEMP_DEPLOY_DIR \
          "
          echo "Deployment process completed on $TARGET_IP."
        env:
          # Ensure SSH_AUTH_SOCK is available for rsync/ssh to use the agent
          SSH_AUTH_SOCK: /tmp/ssh_agent_sock # This should match the socket created by eval "$(ssh-agent -s)"

      - name: Verify deployment (optional)
        run: |
          TARGET_IP="192.168.1.101" # REPLACE THIS WITH YOUR TARGET ALPINE MACHINE'S IP!
          SSH_KEY="~/.ssh/id_rsa_deploy"

          echo "Verifying cron job and log on $TARGET_IP..."
          ssh -i "$SSH_KEY" root@"$TARGET_IP" " \
            echo '--- Crontab entry: ---'; \
            crontab -l | grep water-temp-schliersee; \
            echo ''; \
            echo '--- Last 10 lines of water_temp_sync.log: ---'; \
            cat /var/log/water_temp_sync.log | tail -n 10 \
          "